### ISSUE TITLE
Unfolding Problem round parts

### ISSUE THREAD

**Issue by wwied** [shaise/FreeCAD_SheetMetal#222] opened 2022-01-20 13:55 UTC
first of all i apologize for my bad english - it's not my native language.
i've tried to unfold a circular bended part. works without any problems, part can be generated by different methods and workbenchens.
if i add cirular holes, unfold only works if the hole is not in the seperation line of the bending.

![Bildschirmfoto_2022-01-20_14-53-09](https://user-images.githubusercontent.com/84838853/150351783-ce80b08f-f823-4b0a-8336-6a4e1e5d2a4e.png)

you can see here geometry that works for unfolding. if the cutout is extended to the opposite side, unfold is no longer possible.

and help would be appreciated!

**Comment by shaise** [comment] 2022-01-21 15:42
Unfortunately making holes on a round part is not supported well with the unfolder. only holes on flat parts.
You can also try to ask at the freecad forum: https://forum.freecadweb.org/viewtopic.php?f=3&t=60818
perhaps someone have a solution

**Comment by luzpaz** [comment] 2022-11-09 11:37
Should we turn this in to a feature request ? Or just add it as a wont fix limitation ? Is it technically feasible to do with Sheetmetal wb ?

**Comment by luzpaz** [comment] 2022-11-09 11:43
Dupe of #225

**Closed as not planned by luzpaz** 2022-11-09 11:43 UTC
