### ISSUE TITLE
Round Relief Cuts bug

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#414] opened 2024-12-04 09:50 UTC
### Describe your issue

Doesn't work when depth =< width
It should work at least up to depth = 0.5width
![Зняток екрана як 2024-12-04 11-15-18](https://github.com/user-attachments/assets/a59f285b-f404-43db-8964-ff06aee3ce7c)
![Зняток екрана як 2024-12-04 11-16-19](https://github.com/user-attachments/assets/dbb0aeb8-8e91-4719-a799-bce25c7523d0)
![Зняток екрана як 2024-12-04 11-18-20](https://github.com/user-attachments/assets/182852ba-26ff-4142-8a5c-cb9533b9e66b)

### FreeCAD version info + SheetMetal WB version

```shell
OS: Linux Mint 22 (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 2024.1006.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20241003stable)
Hash: 8058dcf52c2661edabf36d8147d5b8a187378d2d
Python 3.11.9, Qt 5.15.13, Coin 4.0.1, Vtk 9.2.6, OCC 7.7.2
Locale: Ukrainian/Ukraine (uk_UA)
Installed mods: 

  * sheetmetal 0.6.0
```

**Comment by shaise** [comment] 2024-12-04 09:56
Thank you! Let me check

**Comment by shaise** [comment] 2024-12-04 10:24
Ok. This is fixed

**Comment by free777cat** [comment] 2024-12-04 10:54
Sorry, but not quite)
https://youtu.be/QPCxNd_SzZ8

**Comment by free777cat** [comment] 2024-12-04 10:57
We need an equation sign ))

**Comment by shaise** [comment] 2024-12-04 13:57
Yes, I know that. 
Using an equation sign will cause the side wall to be of length zero, causing an error. I can try to overcome this, but it will complicate the code and I don't think its that important.

**Comment by shaise** [comment] 2024-12-04 19:13
@free777cat, Ok, I took the challenge. It supports a 1/2 ratio, and even smaller...

**Comment by pierreporte** [comment] 2024-12-04 21:10
This is a duplicate of #309. I’m closing my issue because it doesn’t have any discussion.

**Comment by shaise** [comment] 2024-12-04 21:44
@pierreporte , thanks.
@free777cat , can we close the issue now, as it supports any width/height ratio now?

**Comment by free777cat** [comment] 2024-12-05 05:53
Thank you very much!!!   It turned out better than expected.

**Closed** 2024-12-05 05:53 UTC
Labels: bug
