### ISSUE TITLE
Error in "make wall"

### ISSUE THREAD

**Issue by free777cat** [shaise/FreeCAD_SheetMetal#311] opened 2024-03-17 16:44 UTC
Unexplained error.
![Зняток екрана як 2024-03-17 18-34-18](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/7def1b56-f612-4aaa-9e7a-51c62ccbcfc3)
![Зняток екрана як 2024-03-17 18-33-38](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/a9089289-ac30-4b12-88ca-806aaaf3cb02)
[examp.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/14628140/examp.zip)

**Comment by free777cat** [comment] 2024-03-17 16:46
This is the second project with such an error

**Comment by shaise** [comment] 2024-03-18 11:48
@jaisekjames ,
Can you take a look at it? seems an issue with auto mitering.

**Comment by free777cat** [comment] 2024-03-22 14:26
What do you mean?

**Comment by free777cat** [comment] 2024-03-22 15:28
Maybe it's these labels?
![Зняток екрана як 2024-03-22 17-25-21](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/2159c9f7-3a48-4193-a24c-348a3e4ee36c)
![Зняток екрана як 2024-03-22 17-25-35](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/7a7ef811-f4db-426b-ba95-edd462fe8ab4)

**Comment by shaise** [comment] 2024-03-22 16:34
@free777cat ,

> What do you mean?

I just asked the original developer of this feature to take a look at the bug. Anyway I took a look myself and I think I know what the problem is. A fix is on the way.

**Comment by free777cat** [comment] 2024-03-22 17:52
This is very good. This Error forced me to manually correct very complex details.

**Comment by shaise** [comment] 2024-03-22 19:14
OK, I believe it is fixed now. please update the workbench and recompute your model.

**Comment by free777cat** [comment] 2024-03-23 21:12
![Зняток екрана як 2024-03-23 23-03-56](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/7841d9bc-2785-4c28-9d9e-e29890faaedd)
![Зняток екрана як 2024-03-23 23-05-51](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/eec33ceb-b146-4a63-b78b-5888a87da93c)
![Зняток екрана як 2024-03-23 23-04-42](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/83dda53f-c865-4dab-9920-38d41588eefb)

Many thanks!!!
Couldn't figure out what the lilac labels are.
Maybe you know?
And then let's close it...

**Comment by free777cat** [comment] 2024-03-23 21:16
Had to uninstall and reinstall. The update didn't work. That's the only way everything turned out well.

**Comment by free777cat** [comment] 2024-03-25 18:38
lilac labels appear when the object has been used in a Boolean operation

**Comment by shaise** [comment] 2024-03-25 20:18
What do you mean?

**Comment by free777cat** [comment] 2024-03-26 08:45
Sorry. This is a false statement.

**Comment by free777cat** [comment] 2024-03-28 15:07
Houston! We have problems again!
Please look at this ((
[Uploading examp1.zip…]()

**Comment by free777cat** [comment] 2024-03-28 15:07
![Зняток екрана як 2024-03-28 17-05-43](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/1062a61c-4e82-46f4-9dd8-e2af77bbbbd1)

**Comment by free777cat** [comment] 2024-03-28 15:57
[examp1.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/14792291/examp1.zip)

**Comment by shaise** [comment] 2024-03-28 18:28
Yes you are correct. 
This is limitation of sheetmetal wb - fold works good only on square faces.
This will work:
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/44cb550d-47c1-4c81-8ebd-92bfd0f91ee1)

And this will not work:
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/490fe9f0-191e-4ed6-bf6d-b23bc5a29f09)

**Comment by shaise** [comment] 2024-03-28 21:17
hi @free777cat 

I have enhanced the bend function to work on refined faces as well. It should work now in most cases.
shai

**Comment by free777cat** [comment] 2024-03-29 07:09
Thank you very much!!!!!!!!!!!
An important new project was in jeopardy.

**Comment by free777cat** [comment] 2024-03-29 07:31
I propose to introduce a new element "workpiece" into the "history tree".
This is a virtual element containing the following values: thickness, bending radius, workpiece orientation (in the "sketch" plane or perpendicular).
+possibly sheet sizes.
For further imitation.
It's a lot of code work, but at the beginning I already have this data but it's not marked as "data" in one specific place.

**Comment by free777cat** [comment] 2024-03-30 08:43
Just closed and again a strange error ((
short video
https://youtu.be/BwsipMRXQn8

![Зняток екрана як 2024-03-30 10-35-11](https://github.com/shaise/FreeCAD_SheetMetal/assets/149939500/87387fea-4543-4a00-92db-55fac9a0637c)

**Comment by free777cat** [comment] 2024-03-30 08:44
[examp2.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/14811276/examp2.zip)

**Comment by shaise** [comment] 2024-03-30 17:28
Yes I noticed that sometimes auto mitering does not work. I will take a look at it, But in this case you should switch off auto mitering because if you flatten the shape you get an invalid sheet.

**Comment by free777cat** [comment] 2024-03-30 17:38
watch the video, everything changes there

**Comment by shaise** [comment] 2024-03-30 18:27
OK, I found the issue.
When auto mitering you must set the max extend value. the default is 5mm. This is good for 2mm sheet but not 5mm.
Just change "Max Extend" value to a higher value if you want the mitering to work:
![image](https://github.com/shaise/FreeCAD_SheetMetal/assets/5813568/d92f335a-760b-477c-82b9-26858047132e)

**Closed** 2024-04-20 07:49 UTC
