### ISSUE TITLE
unfold is generating BSplines

### ISSUE THREAD

**Issue by easyw** [shaise/FreeCAD_SheetMetal#31] opened 2018-05-02 21:40 UTC
following this thread
https://forum.freecadweb.org/viewtopic.php?f=3&t=27928&hilit=sheet+metal&start=10#p229286
it seems that in some case Unfolding routines are generating a shape with BSplines...
But with the solution suggested by @UR_ it seems to be fine.

Could his solution be merged?
Thx
Maurice

**Comment by shaise** [comment] 2018-05-06 18:02
I can confirm. I did several tests and it looks like UR_ solution is OK.

**Comment by shaise** [comment] 2018-05-10 12:00
UR_'s solution merged

**Closed as completed by shaise** 2018-05-10 12:00 UTC
