### ISSUE TITLE
creating a gap breaks the bend on freecad 0.17 body

### ISSUE THREAD

**Issue by ouinouin** [shaise/FreeCAD_SheetMetal#24] opened 2018-02-17 19:12 UTC
Hi, 
while bending with no gap from a body (Part design next) : no issues as shown on picture below
![capture d ecran de 2018-02-17 16-07-26](https://user-images.githubusercontent.com/6713759/36342363-d6938bc8-13fd-11e8-8215-d2bd091bc114.png)

while creating a bend with a gap, whatever the orientation i got this : the direction of the fold created is going backwards (may be it has to do with local coordinates of the Part vs global ccordinates of the document ? 
![capture d ecran de 2018-02-17 16-07-56](https://user-images.githubusercontent.com/6713759/36342364-d73fea44-13fd-11e8-8935-e6f242a72ee4.png)

while doing the bend from the part workshop (first plate crated from a cube), i dont experience the issue : 
![capture d ecran de 2018-02-17 16-11-16](https://user-images.githubusercontent.com/6713759/36342365-d7745acc-13fd-11e8-9cc9-55e68bc318c1.png)

OS: Ubuntu 17.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13247 (Git)
Build type: None
Branch: master
Hash: 5022c8df5cef0690f2c8acff4bcebd82655a5f04
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: French/France (fr_FR)

**Comment by shaise** [comment] 2018-02-17 21:49
can you attach a sample file? (FCStd)

**Comment by ouinouin** [comment] 2018-02-20 05:51
Hi, here is an example, I looked into your code , (despite not being coder) I can guess this has to do with the normalAt function and its use, there is interreseting things in the freecad forum about this but I still dont understand the U,V parameters it takes (freecad documentation is wrong  saying it takes a float : it take a couple of floats.)
here is the file
http://ouinouin.net/nextcloud/index.php/s/GrF14XfX91CQzeK

**Comment by shrines** [comment] 2018-02-25 01:39
Hey Shai,
I just experienced the same problem on a relatively simple metal box.  

I initially assumed the problem was associated with the naming problems that occur when a new face is created because a gap is modified.  I therefore rebuilt the attached example without any deletes or redos in the build sequence.  The problem reoccurred immediately after inverting the bend and specifying a gap.

[chain box 180223.FCStd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1755532/chain.box.180223.FCStd.zip)

Regards,
--Steve

**Comment by shaise** [comment] 2018-02-25 08:26
Hi Steve,

Thanks for the input. I am extremely busy now with my "real" job, but hopefully I'll find time for it soon.

shai

**Comment by shrines** [comment] 2018-03-03 13:28
Hey Shai,
Another data point: I just opened the example chain box file and changed the radius on the broken bend from the default 0.39" to 0.01".  The bend repaired itself.
--Steve

**Comment by shrines** [comment] 2018-03-05 23:26
Hey Shai,
After rebuilding the part a couple more times I think I have a repeatable phenomenon.  The bend breaks after inserting a gap only on parts that have been built using another part's face as an initial (independent) position reference.  If I build the part using exactly the same sequence but without referencing another part face then the part builds correctly.
--Steve

**Comment by shaise** [comment] 2018-03-06 06:23
Steve,

I just made some tests, and it seems something has changed in FC system. when I use older version of FC0.17 (build 12920) the bends are built correctly. But I have no way of telling which exact build broke it, so it is hard to track the reason

shai

**Comment by shaise** [comment] 2018-03-06 07:13
Steve, 

Well, this is strange. I downloaded the latest FC (13662) And it works correctly as well. I just loaded your file, marked the problematic bend004 for recompute and when I refreshed it was fixed.

Can you do this test?

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13362 (Git)
Build type: Release
Branch: master
Hash: 8c6b4ad1a60e2af6c1512cd01b6f47620612a5bd
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)

**Comment by shrines** [comment] 2018-03-06 14:46
Hi Shai,
I'll download ver 13362 and try it with the example file later today.
--Steve

**Comment by shrines** [comment] 2018-03-06 18:08
Shai,

I opened the model in 0.17.13662 and saw the same bend correction on
recompute as you did.  I then added a couple of additional bends and had
the problem reoccur.

See the attached.

--Steve

OS: Windows 7
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13362 (Git)
Build type: Release
Branch: master
Hash: 8c6b4ad1a60e2af6c1512cd01b6f47620612a5bd
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)

**Comment by shrines** [comment] 2018-03-06 19:08
Interesting: When I opened the model a second time and marked the bend for
recompute it healed itself.

**Comment by shaise** [comment] 2018-03-08 09:14
This is a strange inconsistency. I wonder if it happens also when not reopening. Can you try reproducing the issue, then immediately without closing the file, recompute?

**Comment by shrines** [comment] 2018-03-08 16:44
Shai,

This morning recreated the sequence, as follows:
1.  I opened the chain box 180223 example file, verified that the incorrect
bend was visible, marked the bend for recompute and confirmed that the bend
direction was corrected.
2. I then deleted all bends on the top part and started rebuilding it.  I
was able to recreate the error on the second bend.
3. I marked the incorrect bend for recompute.  Recomputing had no effect on
the incorrect bend.
4. I saved and closed the chain box file as is, then reopened it, confirmed
the bend was still backwards, marked it for recompute, recomputed and the
bend corrected itself.

--Steve

**Comment by shaise** [comment] 2018-03-08 17:05
Thanks, Steve.
I now need to find time to debug it.

**Comment by shaise** [comment] 2018-03-08 18:05
Steve,

I think i fixed the issue (looks like rounding errors). Can you please test and confirm?

shai

**Comment by shrines** [comment] 2018-03-08 19:17
Shai,

It looks like you fixed the initial wrong direction bend problem but
introduced a new oddity.

I verified that your update fixed the bend direction and then started
adding new bends to see if I could break it.  No problems with bends that
bent the entire edge. When I added a gap to a trial bend the entire part
rotated 90 degrees on the X axis, changed thickness and generally broke
(see attachment).  It is  possible to delete the defective bend and the
model remains intact.

--Steve

**Comment by shaise** [comment] 2018-03-08 19:24
Hi Steve,

Did you attache anything?

**Comment by shrines** [comment] 2018-03-08 19:56
Oops.  Here it is.

**Comment by shrines** [comment] 2018-03-08 19:58
(I forgot t to add the .zip to the name to get through the filters.)

**Comment by easyw** [comment] 2018-03-08 21:27
@shrines 
if you post to github with a mailer, GH drops the attachments

**Comment by shrines** [comment] 2018-03-08 22:54
Okay, I'm back from San Diego and working from my real desk.. Here's the example file built from your build.
[chain_box_example 180308.FCStd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1795068/chain_box_example.180308.FCStd.zip)

**Comment by ouinouin** [comment] 2018-03-08 23:10
opened the chain_box_example 180308.FCStd example, removed the bend 8 from the body named "top" and tried another bend on your part, i got a also a bad result.
![capture d ecran de 2018-03-09 00-07-15](https://user-images.githubusercontent.com/6713759/37181634-18f22ff8-232e-11e8-90bb-3a42315ee18b.png)
the preselection in yellow is the face I tried to bend.

on my side I did some tests and the first bug seems to have been cleared even while putting the initial body in some strange positions (not normal to the X Y or Z plans).
OS: Ubuntu 17.10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13375 (Git)
Build type: None
Branch: master
Hash: 2bfea410fce1434fec0f853b032549aa2cd3c47e
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: French/France (fr_FR)

**Comment by shrines** [comment] 2018-03-10 19:11
Hey Shai,

I think you might find the attachment interesting.  I created two identical parts with just two bends each.  On the first part I included gaps in the first bend and on the second part I did not.  The direction of the second bend is incorrectly reversed on the part that has gaps in its first bend.  

I'll bet this phenomenon is at least partially related to your flipped bend direction problem.  It might also explain my previous confusion as to which end of a face gap1 applies to when building complex bent parts.

[Simple bend Examples.FCStd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1799702/Simple.bend.Examples.FCStd.zip)

--Steve

**Comment by shrines** [comment] 2018-03-10 19:45
A bit more on the bend direction change:  The bend only changes direction when the gap of the first bend is "next to" the second bend.  In the attached example Body000 Bend000 gap1 and gap2=0.01; Body001 Bend002 gap1 and gap2 =0; Body002 Bend004 only gap1=0.01; Body003 Bend006 only gap2=0.01.  The second bend only reverses direction on Body000 and Body002 where gap1 (the gap between bends) is non-zero. 

[Four Simple bend Examples.FCStd.zip](https://github.com/shaise/FreeCAD_SheetMetal/files/1799722/Four.Simple.bend.Examples.FCStd.zip)

From my naive perspective that would narrow the problem down to lines 109-121 in SheetMetalCmd.py
--Steve

**Comment by shaise** [comment] 2018-03-11 10:16
ouinouin,

This problem is not sheetmetal related, or have anything to do with the fix. Here is how sheet metal works when you make a bend: It creates 2 seperate solids - a bend and a wall, then fuses them to the main body. The bend and the wall are created correctly:
![bend24_1](https://user-images.githubusercontent.com/5813568/37252199-cc4e676c-2525-11e8-8a0a-cf8a650b62c6.png)

After fusing all solids the error happen:
![bend24_2](https://user-images.githubusercontent.com/5813568/37252211-ee7c0b0a-2525-11e8-9aed-cdd48e8960bd.png)

OCC is known to have issues with flat face to face fusing of objects.

**Comment by shaise** [comment] 2018-03-11 12:50
Steve,

the bend direction is also somewhat uncontrollable. It is randomly based on the direction of the edges of the face that bends. When you add a gap, the geometry changes (more edges then without gaps) and quite possibly the edges might point to a different direction.

shai

**Comment by ulrich1a** [comment] 2018-08-19 14:43
> OCC is known to have issues with flat face to face fusing of objects.

The unfold tool needs also to generate new geometry. I do not using the OCCT fusion but do collect all faces and build a new shell and than a new solid. This approach is more robust in OCCT. 

Ulrich

**Comment by luzpaz** [comment] 2021-02-11 15:55
What's the status of this ticket?

**Comment by luzpaz** [comment] 2021-03-03 18:54
bump

**Comment by luzpaz** [comment] 2021-04-13 18:59
@shaise bump

**Comment by shaise** [comment] 2021-04-14 09:40
hi @luzpaz ,

I have reconstructed the part under freecad 19 (just went bend by bend, and select the correct face) and I see no issues.

shai

**Comment by luzpaz** [comment] 2021-05-15 20:18
@shaise close ticket then?

**Comment by shaise** [comment] 2021-05-15 20:27
maybe...

**Comment by luzpaz** [comment] 2022-11-09 11:50
Closing ticket

**Closed as completed by luzpaz** 2022-11-09 11:50 UTC
